### ISSUE TITLE
Pictures not in folder

### ISSUE THREAD

**Issue by hkavsc** [markszabo/tapo-c200-timelapse#5]
Hi, 

the program looks like it works fine, but the pictures are not in folder? 

![2024-03-06-224851_1920x1080_scrot](https://github.com/markszabo/tapo-c200-timelapse/assets/152281337/883ed176-5301-4fd0-ae46-12bf526425c8)

**Comment by markszabo** [comment]
hi, hm, that's weird. My first guess is that it is a UI bug: the file viewer might not update the list of files immediately. Can you try listing the files with `ls -la` in the folder? This should also show you the file and folder permissions to see if those are off (though that should result in an error).

Btw your screenshot contains the password for your stream (first line of the config file), so you might want to change that if you haven't already

**Comment by sreimler** [comment]
I think I'm having the same issue. Script appears to run fine and folder with the name of the day within the timelapse folder is being created. However, no actual images get saved to the folder.

Does anyone have an idea on how to resolve or debug that?

**Comment by sreimler** [comment]
Can confirm that this works with ffmpeg as implemented in #6. Thanks!

**Comment by markszabo** [comment]
Thanks for the confirmation, closing this issue then
